modLoader="javafml"
loaderVersion="[40,)"
license="ARR"
issueTrackerURL="https://github.com/teaconmc/XKDeco/issues?q=is%3Aissue"

[[mods]]
modId="xkdeco"
authors="XeKr, Snownee, TeaConMC"
version="${file.jarVersion}"
displayName="XeKr's Decoration"
displayURL="https://www.curseforge.com/minecraft/mc-mods/xks-decoration"
description='''
Models and textures are created by XeKr: https://github.com/XeKr
'''

[modproperties.xkdeco]
kiwiCustomization=true

[[dependencies.xkdeco]]
modId="forge"
mandatory=true
versionRange="[45,)"
ordering="NONE"
side="BOTH"

[[dependencies.xkdeco]]
modId="minecraft"
mandatory=true
versionRange="1.20.1"
ordering="NONE"
side="BOTH"

[[dependencies.xkdeco]]
modId="kiwi"
mandatory=true
versionRange="[11.8.3,12)"
ordering="NONE"
side="BOTH"